---
title: "Homework_5"
author: "Tony Zbysinski"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r include = FALSE}
# loading libraries
library(tidyverse)
library(knitr)
library(broom)
library(readr)
library(lubridate)
library(scales)
```

```{r include = FALSE}
# loading and cleaning data
balt_homicidesv1 <- read.csv("../data/homicide.csv") %>%
  mutate(city_name = paste(city, state, sep = ", ")) %>%
  filter(city_name == "Baltimore, MD") %>%
  mutate(date = ymd(reported_date))
balt_homicidesv2 <- balt_homicidesv1 %>%
  mutate(month_year = format(as.Date(balt_homicidesv1$date), "%Y-%m")) %>%
  mutate(month_year = ym(month_year)) %>%
  mutate(month = month(date)) %>%
  mutate(winter_month = month %in% c(1:4, 11, 12))
balt_homicidesv3 <- balt_homicidesv2 %>%
  group_by(month_year, winter_month) %>%
  count(name = "total_homicides") %>%
  ungroup()
```

```{r include = FALSE, fig.height = 2.5, fig.width = 8}
# creating the graph
balt_homicide_plot <- balt_homicidesv3 %>%
  ggplot() +
  geom_col(aes(x = month_year, y = total_homicides, fill = winter_month)) + 
  geom_vline(aes(xintercept = ym("2015-04"), colour = "red"), show.legend = FALSE, 
             size = 2, linetype = 2) +
  geom_smooth(aes(x = month_year, y = total_homicides), color = "blue", se = FALSE, span = 0.1) +
  scale_fill_manual(values = c("grey", "skyblue"), 
                    labels = c("Summer", "Winter")) +
  annotate(geom = "text", x = ym("2014-02"), y = 43, label = "Arrest of Freddie Gray", color = "White") +
  theme_dark() +
  theme(legend.position = "bottom") +
  labs(title = "Homicides in Baltimore, MD", x = "Date", 
       y = "Monthly homicides", fill = "")
balt_homicide_plot
```

